/**
 * @aiq.webdesigner
 * This script requires AIQ Web Designer
*/
setShadowDOM(true);
navigateTo("https://s2.supplier.avantorsciences.com/productmanagement/login.zul");
setValue(fallback(`textbox("j_username")`,
   `textbox(0, _in(div({'id':'aFLEt'})))`,
   `byXPath('//*[@id="aFLEv"]')`,
   `textbox("login z-textbox z-textbox-hover")`,
   `byXPath('//*[@name="j_username"]')`,
   `textbox("aFLEv")`,
   `byXPath("//input[@id='aFLEv']")`,
   `byXPath('//*[@class="login z-textbox z-textbox-hover"]')`,
   `byXPath('/html/body/div/div/div/div/div/form/div/table/tbody/tr/td/table/tbody/tr/td/div/table/tbody/tr/td/table/tbody/tr/td[3]/div/input')`,
   `byXPath("id('aFLEv')")`,
   `byXPath('//tbody//tr[1]//td[3]//div//input[@id="aFLEv"]')`,
   `byXPath('//tbody//tr[1]//td[3]//div//input[@class="login z-textbox z-textbox-hover"]')`,
   `byXPath('//tbody//tr[1]//td[3]//div//input[@name="j_username"]')`,
   `textbox({'type':'text'})`,
   `byJQuery('div[class="compRowCnt z-div"] > input[class="login z-textbox z-textbox-hover"]')`,
   `byJQuery('#aFLEv')`,
   `byJQuery('input[name="j_username"]')`,
   `byJQuery('input[value=""]')`,
   `textbox(0, _in(div("aFLEt")))`),"pho_testuser");
setValue(fallback(`password("j_password")`,
   `password(0, _in(div({'id':'aFLEy'})))`,
   `byXPath('//*[@id="aFLE_0"]')`,
   `password("login z-textbox z-textbox-hover")`,
   `byXPath('//*[@name="j_password"]')`,
   `password("aFLE_0")`,
   `byXPath("//input[@id='aFLE_0']")`,
   `byXPath('//*[@class="login z-textbox z-textbox-hover"]')`,
   `byXPath('/html/body/div/div/div/div/div/form/div/table/tbody/tr/td/table/tbody/tr/td/div/table[2]/tbody/tr/td/table/tbody/tr/td[3]/div/input')`,
   `byXPath("id('aFLE_0')")`,
   `byXPath('//tbody//tr[1]//td[3]//div//input[@id="aFLE_0"]')`,
   `byXPath('//tbody//tr[1]//td[3]//div//input[@class="login z-textbox z-textbox-hover"]')`,
   `byXPath('//tbody//tr[1]//td[3]//div//input[@name="j_password"]')`,
   `password({'type':'password'})`,
   `byJQuery('div[class="compRowCnt z-div"] > input[class="login z-textbox z-textbox-hover"]')`,
   `byJQuery('#aFLE_0')`,
   `byJQuery('input[name="j_password"]')`,
   `password(0, _in(div("aFLEy")))`),"phouser");
click(fallback(`button("Sign In")`,
   `button(0, _in(div({'id':'aFLEl'})))`,
   `byXPath('//*[@id="aFLEo"]')`,
   `button("login_btn y-btn-primary z-button")`,
   `button("aFLEo")`,
   `byXPath("//button[@id='aFLEo']")`,
   `byXPath('//*[@class="login_btn y-btn-primary z-button"]')`,
   `byXPath('//*[text()="Sign In"]')`,
   `byXPath('/html/body/div/div/div/div/div/form/div/table/tbody/tr/td/table/tbody/tr[5]/td/div/button')`,
   `byXPath("id('aFLEo')")`,
   `byXPath('//tbody//tr[5]//td[1]//div//button[@id="aFLEo"]')`,
   `byXPath('//tbody//tr[5]//td[1]//div//button[@class="login_btn y-btn-primary z-button"]')`,
   `byXPath('//tbody//tr[5]//td[1]//div//button[text()="Sign In"]')`,
   `byJQuery('div[class="login-footer login-footer_row z-div"] > button[class="login_btn y-btn-primary z-button"]')`,
   `byJQuery('#aFLEo')`,
   `button(0, _in(div("aFLEl")))`));
navigateTo("https://s2.supplier.avantorsciences.com/productmanagement/");
click(fallback(`submit("Next Page[1]")`,
   `submit("z-paging-button z-paging-next[1]")`,
   `byXPath('//*[@name="sTcBzy1-next"]')`,
   `submit("sTcBzy1-next")`,
   `byXPath("//nav[@id='sTcBzy1']/ul/li[4]/button")`,
   `byXPath('/html/body/div/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div[4]/div/div[2]/div/div/div[2]/div[2]/div/div/div[4]/div[2]/div/div[3]/div[2]/div/nav/ul/li[4]/button')`,
   `byXPath("id('sTcBzy1')/ul[1]/li[4]/button[@class='z-paging-button z-paging-next']")`,
   `byJQuery('button[name="sTcBzy1-next"]')`));
click(fallback(`button(0, _in(div("iQ8Ous8")))`,
   `button(0, _in(div({'id':'iQ8Ous8'})))`,
   `button("More Actions[30]")`,
   `byXPath('//*[@id="iQ8Ovs8"]')`,
   `button("cng-font-icon y-btn-transparent yw-show-menu-action z-button[30]")`,
   `button("iQ8Ovs8")`,
   `byXPath("//button[@id='iQ8Ovs8']")`,
   `byXPath('/html/body/div/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div[4]/div/div[2]/div/div/div[2]/div[2]/div/div/div[4]/div[2]/div/div[2]/div/div[2]/table/tbody/tr/td[6]/div/div/button')`,
   `byXPath("id('iQ8Ovs8')")`,
   `byXPath('//tbody//tr[1]//td[6]//div//div//button[@id="iQ8Ovs8"]')`,
   `byXPath('//tbody//tr[1]//td[6]//div//div//button[@class="yw-show-menu-action y-btn-transparent cng-font-icon z-button"]')`,
   `byJQuery('#iQ8Ovs8')`));
click(fallback(`span("z-menu-text")`,
   `span("Set decision")`,
   `byXPath("//a[@id='iQ8Oys8-a']/span")`,
   `byXPath('//*[@class="z-menu-text"]')`,
   `byXPath('//*[text()="Set decision"]')`,
   `byXPath('/html/body/div[3]/ul/li[2]/a/span')`,
   `byXPath("id('iQ8Oys8-a')/span[@class='z-menu-text']")`,
   `byJQuery('div[class="yw-workflows-menu-popup yw-pointer-menupopup yw-pointer-menupopup-top-right workflow-action-menupopup-top z-menupopup z-menupopup-shadow z-menupopup-open"] > ul[class="z-menupopup-content"] > li[class="z-menu z-menu-hover"] > a[class="z-menu-content"] > span[class="z-menu-text"]')`,
   `byJQuery('#iQ8Oys8-a > .z-menu-text')`));
click(fallback(`link(0, _in(listItem("iQ8O_t8")))`,
   `link(0, _in(listItem({'id':'iQ8O_t8'})))`,
   `byXPath('//*[@id="iQ8O_t8-a"]')`,
   `link("z-menuitem-content[2]")`,
   `link("iQ8O_t8-a")`,
   `link("javascript:;[5]")`,
   `link("Send back to Vendor for updates")`,
   `byXPath("//a[@id='iQ8O_t8-a']")`,
   `byXPath('/html/body/div[4]/ul/li/a')`,
   `byXPath("id('iQ8O_t8-a')")`,
   `byJQuery('body[class="webkit chrome atlantic"] > div[class="yw-workflows-menu-popup yw-pointer-menupopup yw-pointer-menupopup-secondary z-menupopup z-menupopup-shadow z-menupopup-open"] > ul[class="z-menupopup-content"] > li[class="z-menuitem z-menuitem-hover"] > a[class="z-menuitem-content"]')`,
   `byJQuery('#iQ8O_t8-a')`));
selectFrame("Editor");
var dyn1=eval('Math.floor(Math.random()*100)');
log(storedVars["dyn1"]);
click(fallback(`byXPath('//body[@role="textbox"]/p')`,
   `byXPath('//*[@name="loginfmt"]')`,
   `byXPath('//*[@role="textbox"]/p')`,
   `bodybyXPath('//body[@role="textbox"]/p')`));
setHTML(selectFrame());
